### ISSUE TITLE
Is it also needed to install linux-firmware-surface-go?

### ISSUE THREAD

**Issue by Kcorab** [dmhacker/arch-linux-surface#34]
I use the Surface Go.

After install of this patched kernel, is it needed to install [linux-firmware-surface-go](https://aur.archlinux.org/packages/linux-firmware-surface-go/)?

Or whats the difference between this patched kernel and the patched linux-firmware?

**Comment by v12venator** [comment]
I don't remember this project creating any linux-firmware packages, so it would probably be a good idea to install this package as well from the AUR. It may give you some extra functionality on your Go.

**Comment by testitest0r** [comment]
I tried to install the packages from the AUR because the SD card reader from my Surface GO is not working (mmc0: error -110 whilst initialising SD card), but got an error stating conflicts with linux-firmware-surface-go and linux-firmware. 

@Kcorab did you have any issues with the hardware - espacialy the cardreader -  of the device?

**Comment by dmhacker** [comment]
This seems somewhat unrelated to the goal of this repository, since my firmware scripts are basically copied verbatim with jakeday's repository (tweaked to work with Arch Linux of course) and this issue is asking about a package. I would advise checking out the issues section for linux-surface for more details.
