### ISSUE TITLE
SB2 Stylus input is wrong

### ISSUE THREAD

**Issue by vonAlenberg** [dmhacker/arch-linux-surface#8]
Both on the 4.18 and 4.17 kernel the stylus input is recognized, but displayed incorrectly. So when I rotate the screen (had to install `iio-sensor-proxy` for that) the xorg-rotation is right, also touch is registered right, only the stylus input is wrong.

How to solve that?

**Comment by dmhacker** [comment]
I'm not actually sure myself. This sounds like more of an upstream issue. I'll keep an eye for any potential fixes, but since this utility is simply meant to allow the kernel to be compiled for Arch devices, I'm not going to promise anything.

**Comment by qzed** [comment]
Just freshly installed Arch and ran into the same problem. Fixed it by installing the patched libwacom (via https://github.com/qzed/libwacom-surface).

**Comment by dmhacker** [comment]
As of commit 11a9999, there is now an option to build and install the patched libwacom-surface package. This replaces the default libwacom package. Like qzed said, the patched libwacom package should help with stylus issues.

Closing this issue since it's been open for over a year now with little activity in between and a potential fix listed above.
