### ISSUE TITLE
Help required with ZFS support

### ISSUE THREAD

**Issue by shadowrylander** [dmhacker/arch-linux-surface#98]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; I want to try using ZFS for my filesystem of choice; however, given that there are specific kernels required to use it, how would I go about either using those kernels and applying your patches, or using your kernel and enabling ZFS support on it? <br>
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for the help!

**Comment by dmhacker** [comment]
Hey,

Interesting to see that you are using ZFS. I would think that in order to get ZFS working Linux with the Surface patches, you would have apply the patches to the ZFS on Linux upstream branch. See about modifying the file: https://github.com/dmhacker/arch-linux-surface/blob/master/base/templates/PKGBUILD to point to whatever ZFS on Linux is using (git+https://github.com/zfsonlinux/zfs.git) rather than the regular Linux repository ( git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git). Once you modify the PKGBUILD in your version of this repository and run `compile_setup.sh`, it should generate a directory with a properly formed PKGBUILD in it.

As for the actual Surface patches, I'm  not sure if they can be correctly applied on top of the ZFS-adjusted kernel but you're welcome to try. That might be an issue to bring up with the @linux-surface team.

**Comment by shadowrylander** [comment]
Actually, I started using the arch `zfs-dkms` package (VERY IMPORTANT: VERSION >= 0.8.3-2); so basically, every time I install a new kernel, I uninstall `zfs-dkms`, reboot, then reinstall it. Everything works perfectly then!

**Comment by dmhacker** [comment]
Oh great! In that case, I will close this issue since you seem to have solved it.

**Comment by shadowrylander** [comment]
Yep! Hopefully anyone else who needs help will find this!
